### ISSUE TITLE
RPM repository is using SHA1 key

### ISSUE THREAD

**Issue by ViliusS** [sonatype-nexus-community/nexus-repository-installer#25] opened 2022-11-28 08:58 UTC
Currently the [key](https://repo.sonatype.com/repository/community-hosted/pki/rpm-gpg/RPM-GPG-KEY-Sonatype.asc) assigned to RPM repository is using SHA-1 hashing. This produces errors on CentOS/RHEL/Rocky 9 systems.

```
warning: Signature not supported. Hash algorithm SHA1 not available.
error: rpmdbNextIterator: skipping h#     196
Header V4 RSA/SHA1 Signature, key ID 0aa4f31a: BAD
Header SHA1 digest: OK
```

**Comment by bhamail** [comment] 2022-11-28 22:11
@ViliusS Thanks for reporting this issue. [Looking into it](https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9). PR's and/or suggestions welcome!

**Comment by ViliusS** [comment] 2022-11-28 22:19
I probably won't be able to provide PR because, you know, this requires generating new key by Sonartype :)

But the solution is simple, generate SHA256 or similar strong key, because SHA-1 is not enabled on Enterprise Linux 9.x series.

**Comment by bhamail** [comment] 2022-12-05 22:35
@ViliusS So I've been digging into this, and I think the issue can be solved with a tweak to how we build the .rpm under CentOS7. I'll post a PR with details.
The missing puzzle piece is I haven't been able to reproduce the error you posted above with a local .rpm under CentOS 9 Stream. Any suggestions on how to test this change before publishing to the yum repo?

See: PR #26

**Comment by ViliusS** [comment] 2022-12-06 05:20
Check if you are running DEFAULT crypto policies `update-crypto-policies --show`. If not, `update-crypto-policies --set DEFAULT`. You might need a reboot after that.

The easiest way to check is `rpm -qi nexus-repository-manager`:
```
$ update-crypto-policies --show
DEFAULT
$ rpm -qi nexus-repository-manager
warning: Signature not supported. Hash algorithm SHA1 not available.
error: rpmdbNextIterator: skipping h#     196
Header V4 RSA/SHA1 Signature, key ID 0aa4f31a: BAD
Header SHA1 digest: OK
package nexus-repository-manager is not installed

```

**Comment by bhamail** [comment] 2022-12-06 19:44
@ViliusS Thanks for the ideas.

I managed to stand up a separate `yum` repository in `nexus-repository-manager` and publish an "old" (sha1 signed) rpm, and verified the install fails:
```shell
# yum install nexus-repository-manager
Last metadata expiration check: 0:00:15 ago on Tue 06 Dec 2022 02:21:12 PM EST.
Dependencies resolved.
============================================================================================================
 Package                         Arch       Version                      Repository                    Size
============================================================================================================
Installing:
 nexus-repository-manager        noarch     3.43.0_01-1.el7              sonatype-community-local     197 M
Installing dependencies:
 copy-jdk-configs                noarch     4.0-3.el9                    appstream                     28 k
 java-1.8.0-openjdk-headless     x86_64     1:1.8.0.352.b08-2.el9        appstream                     33 M
 javapackages-filesystem         noarch     6.0.0-3.el9                  appstream                     14 k
 lksctp-tools                    x86_64     1.0.19-2.el9                 baseos                        94 k
 lua                             x86_64     5.4.2-4.el9                  appstream                    188 k
 lua-posix                       x86_64     35.0-8.el9                   appstream                    151 k
 tzdata-java                     noarch     2022f-1.el9                  appstream                    230 k

Transaction Summary
============================================================================================================
Install  8 Packages

Total download size: 231 M
Installed size: 343 M
Is this ok [y/N]: y
Downloading Packages:
[MIRROR] lksctp-tools-1.0.19-2.el9.x86_64.rpm: Status code: 404 for http://mirror.stjschools.org/centos-stream/9-stream/BaseOS/x86_64/os/Packages/lksctp-tools-1.0.19-2.el9.x86_64.rpm (IP: 38.21.153.105)
(1/8): copy-jdk-configs-4.0-3.el9.noarch.rpm                                102 kB/s |  28 kB     00:00    
(2/8): lksctp-tools-1.0.19-2.el9.x86_64.rpm                                 191 kB/s |  94 kB     00:00    
(3/8): javapackages-filesystem-6.0.0-3.el9.noarch.rpm                        29 kB/s |  14 kB     00:00    
(4/8): lua-5.4.2-4.el9.x86_64.rpm                                           803 kB/s | 188 kB     00:00    
(5/8): lua-posix-35.0-8.el9.x86_64.rpm                                      1.4 MB/s | 151 kB     00:00    
(6/8): tzdata-java-2022f-1.el9.noarch.rpm                                   1.3 MB/s | 230 kB     00:00    
(7/8): java-1.8.0-openjdk-headless-1.8.0.352.b08-2.el9.x86_64.rpm            12 MB/s |  33 MB     00:02    
(8/8): nexus-repository-manager-3.43.0_01-1.el7.noarch.rpm                   17 MB/s | 197 MB     00:11    
------------------------------------------------------------------------------------------------------------
Total                                                                        19 MB/s | 231 MB     00:12     
warning: Signature not supported. Hash algorithm SHA1 not available.
warning: Signature not supported. Hash algorithm SHA1 not available.
Problem opening package nexus-repository-manager-3.43.0_01-1.el7.noarch.rpm
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'yum clean packages'.
Error: GPG check FAILED
```



I then published a new .rpm with sha256 signature, and it succeeds:
```shell
# yum install nexus-repository-manager
Last metadata expiration check: 0:00:04 ago on Tue 06 Dec 2022 02:30:25 PM EST.
Dependencies resolved.
============================================================================================================
 Package                         Arch       Version                      Repository                    Size
============================================================================================================
Installing:
 nexus-repository-manager        noarch     3.43.0_01-1.el7              sonatype-community-local     197 M
Installing dependencies:
 copy-jdk-configs                noarch     4.0-3.el9                    appstream                     28 k
 java-1.8.0-openjdk-headless     x86_64     1:1.8.0.352.b08-2.el9        appstream                     33 M
 javapackages-filesystem         noarch     6.0.0-3.el9                  appstream                     14 k
 lksctp-tools                    x86_64     1.0.19-2.el9                 baseos                        94 k
 lua                             x86_64     5.4.2-4.el9                  appstream                    188 k
 lua-posix                       x86_64     35.0-8.el9                   appstream                    151 k
 tzdata-java                     noarch     2022f-1.el9                  appstream                    230 k

Transaction Summary
============================================================================================================
Install  8 Packages

Total download size: 231 M
Installed size: 343 M
Is this ok [y/N]: y
Downloading Packages:
(1/8): copy-jdk-configs-4.0-3.el9.noarch.rpm                                304 kB/s |  28 kB     00:00    
(2/8): lksctp-tools-1.0.19-2.el9.x86_64.rpm                                 743 kB/s |  94 kB     00:00    
(3/8): javapackages-filesystem-6.0.0-3.el9.noarch.rpm                       161 kB/s |  14 kB     00:00    
(4/8): lua-5.4.2-4.el9.x86_64.rpm                                           1.2 MB/s | 188 kB     00:00    
(5/8): lua-posix-35.0-8.el9.x86_64.rpm                                      2.1 MB/s | 151 kB     00:00    
(6/8): tzdata-java-2022f-1.el9.noarch.rpm                                   1.5 MB/s | 230 kB     00:00    
(7/8): java-1.8.0-openjdk-headless-1.8.0.352.b08-2.el9.x86_64.rpm           6.5 MB/s |  33 MB     00:05    
(8/8): nexus-repository-manager-3.43.0_01-1.el7.noarch.rpm                   17 MB/s | 197 MB     00:11    
------------------------------------------------------------------------------------------------------------
Total                                                                        19 MB/s | 231 MB     00:11     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Running scriptlet: copy-jdk-configs-4.0-3.el9.noarch                                                  1/1 
  Running scriptlet: java-1.8.0-openjdk-headless-1:1.8.0.352.b08-2.el9.x86_64                           1/1 
  Preparing        :                                                                                    1/1 
  Installing       : tzdata-java-2022f-1.el9.noarch                                                     1/8 
  Installing       : lua-posix-35.0-8.el9.x86_64                                                        2/8 
  Installing       : lua-5.4.2-4.el9.x86_64                                                             3/8 
  Installing       : copy-jdk-configs-4.0-3.el9.noarch                                                  4/8 
  Installing       : javapackages-filesystem-6.0.0-3.el9.noarch                                         5/8 
  Installing       : lksctp-tools-1.0.19-2.el9.x86_64                                                   6/8 
  Installing       : java-1.8.0-openjdk-headless-1:1.8.0.352.b08-2.el9.x86_64                           7/8 
  Running scriptlet: java-1.8.0-openjdk-headless-1:1.8.0.352.b08-2.el9.x86_64                           7/8 
  Running scriptlet: nexus-repository-manager-3.43.0_01-1.el7.noarch                                    8/8 
pre 1

  Installing       : nexus-repository-manager-3.43.0_01-1.el7.noarch                                    8/8 
  Running scriptlet: nexus-repository-manager-3.43.0_01-1.el7.noarch                                    8/8 
post 1
Created symlink /etc/systemd/system/multi-user.target.wants/nexus-repository-manager.service → /opt/sonatype/nexus3/extra/daemon/nexus-repository-manager.service.

  Running scriptlet: copy-jdk-configs-4.0-3.el9.noarch                                                  8/8 
  Running scriptlet: java-1.8.0-openjdk-headless-1:1.8.0.352.b08-2.el9.x86_64                           8/8 
  Running scriptlet: nexus-repository-manager-3.43.0_01-1.el7.noarch                                    8/8 
  Verifying        : nexus-repository-manager-3.43.0_01-1.el7.noarch                                    1/8 
  Verifying        : lksctp-tools-1.0.19-2.el9.x86_64                                                   2/8 
  Verifying        : copy-jdk-configs-4.0-3.el9.noarch                                                  3/8 
  Verifying        : java-1.8.0-openjdk-headless-1:1.8.0.352.b08-2.el9.x86_64                           4/8 
  Verifying        : javapackages-filesystem-6.0.0-3.el9.noarch                                         5/8 
  Verifying        : lua-5.4.2-4.el9.x86_64                                                             6/8 
  Verifying        : lua-posix-35.0-8.el9.x86_64                                                        7/8 
  Verifying        : tzdata-java-2022f-1.el9.noarch                                                     8/8 

Installed:
  copy-jdk-configs-4.0-3.el9.noarch                java-1.8.0-openjdk-headless-1:1.8.0.352.b08-2.el9.x86_64 
  javapackages-filesystem-6.0.0-3.el9.noarch       lksctp-tools-1.0.19-2.el9.x86_64                         
  lua-5.4.2-4.el9.x86_64                           lua-posix-35.0-8.el9.x86_64                              
  nexus-repository-manager-3.43.0_01-1.el7.noarch  tzdata-java-2022f-1.el9.noarch                           

Complete!
```

(For anyone playing along at home, don't forget to give Nexus Repository Manager a few minutes to rebuild the Yum Metadata after publishing a new version of an `.rpm` to the repository.)

Given the above, I think the sha1 issue will be fixed byt PR #26. Please holler with any objections/suggestions.

**Closed as completed** 2022-12-06 20:13 UTC

**Comment by ViliusS** [comment] 2022-12-06 20:38
@bhamail not sure if that's related, but could you verify if your fix also regenerates GPG public key for the repository at https://repo.sonatype.com/repository/community-hosted/pki/rpm-gpg/RPM-GPG-KEY-Sonatype.asc ?
I think GPG public key expired on 2021-08-15

**Comment by bhamail** [comment] 2022-12-06 22:08
@ViliusS  Ooof. Let's create a new issue for that, as I believe it is genuine, but separate.

**Comment by ViliusS** [comment] 2022-12-21 22:33
nexus-repository-manager-3.44.0_01-1.el7.noarch.rpm is still signed with SHA1 key

**Comment by ViliusS** [comment] 2022-12-30 10:21
nexus-repository-manager-3.45.0_01-1.el7.noarch.rpm is also signed with SHA1 key

**Comment by bhamail** [comment] 2023-01-03 23:19
@ViliusS Perhaps I'm missing something, but I downloaded the .rpms from the repository and ran the `rpm -qpi` command, and the new rpms appear to be signed with sha256.

```bash
[danrollo@localhost Downloads]$ rpm -qpi nexus-repository-manager-3.44.0_01-1.el7.noarch.rpm 
Name        : nexus-repository-manager
Version     : 3.44.0_01
Release     : 1.el7
Architecture: noarch
Install Date: (not installed)
Group       : Unspecified
Size        : 232903303
License     : Proprietary
Signature   : RSA/SHA256, Wed 14 Dec 2022 03:17:13 PM EST, Key ID 964b5e720aa4f31a
Source RPM  : nexus-repository-manager-3.44.0_01-1.el7.src.rpm
Build Date  : Wed 14 Dec 2022 03:16:09 PM EST
Build Host  : 7c4957b11262
URL         : https://www.sonatype.com
Summary     : Nexus Repository Manager 3
Description :
Nexus Repository Manager 3
[danrollo@localhost Downloads]$ rpm -qpi nexus-repository-manager-3.45.0_01-1.el7.noarch.rpm 
Name        : nexus-repository-manager
Version     : 3.45.0_01
Release     : 1.el7
Architecture: noarch
Install Date: (not installed)
Group       : Unspecified
Size        : 232963370
License     : Proprietary
Signature   : RSA/SHA256, Wed 28 Dec 2022 03:17:23 PM EST, Key ID 964b5e720aa4f31a
Source RPM  : nexus-repository-manager-3.45.0_01-1.el7.src.rpm
Build Date  : Wed 28 Dec 2022 03:16:07 PM EST
Build Host  : a08df6410eb8
URL         : https://www.sonatype.com
Summary     : Nexus Repository Manager 3
Description :
Nexus Repository Manager 3
```

**Comment by ViliusS** [comment] 2023-01-04 21:52
Very strange. I can verify that RPM package is indeed signed with SHA256 but when I try to update to 3.44 or 3.45 via `dnf update` I see SHA1 errors mentioned above. I also see the same SHA1 error and cannot upgrade if I use `rpm -Uvh nexus-repository-manager-3.45.0_01-1.el7.noarch.rpm` when trying to upgrade from local file.

Maybe it's an issue with rpm manager itself; it cannot upgrade SHA1 to SHA256 packages if SHA1 is disabled in the system?

For now the only workaround I could find is temporary enable SHA1 `update-crypto-policies --set DEFAULT:SHA1`, upgrade to at least Nexus Repository Manager 3.44, and then disable SHA1 again `update-crypto-policies --set DEFAULT`. After that upgrading from 3.44 to 3.45 works without issues.

**Comment by bhamail** [comment] 2023-01-04 22:01
@ViliusS Thanks for reporting what you found (and your workaround)! Maybe this is a "temporary" issue - caused by going from a previously installed version signed with SHA1, to a newer version signed with SHA256. Great to hear 3.44 to 3.45 worked without the need for workarounds. ;)

**Comment by ViliusS** [comment] 2023-01-04 22:01
Yep, looks like it:
https://access.redhat.com/solutions/6868611 - Packages signed with SHA-1 cannot be installed or **upgraded**
The SHA-1 message digest has been deprecated in Red Hat Enterprise Linux 9. The digest produced by SHA-1 is not considered secure because of many documented successful attacks based on finding hash collision
This causes issues when using DNF/RPM to handle packages with RSA/SHA1 signatures as the signature cannot be checked with the default cryptographic policy. Any such packages **cannot be** installed, removed, or **replaced unless the signature check is disabled in DNF/RPM or SHA-1 is enabled using non-default crypto-policies**.
